-- CREATE DATABASE, IF IT DOESN'T EXIST
CREATE DATABASE IF NOT EXISTS donuts;



-- CONNECT TO DATABASE
USE donuts;


-- CREATE DONUTS TABLE 
CREATE TABLE IF NOT EXISTS donuts(
    id integer AUTO_INCREMENT UNIQUE KEY PRIMARY KEY,
    filling VARCHAR (25), 
    stale TINYINT(1)
    );

